=== Gam1nerie/XML/axl.dtd
<?xml version="1.0" encoding="utf-8"?>
     <!ELEMENT commercial (client+)>
     <!ELEMENT client (demande+)>
     <!ATTLIST client nom  CDATA #REQUIRED>
     <!ATTLIST client prenom  CDATA #REQUIRED>
     <!ATTLIST client mail  CDATA #REQUIRED>
     <!ATTLIST client mobile  CDATA #REQUIRED>
     <!ELEMENT demande (destination, periode, duree, nbparticipant, tarifmax, propositions?)>
     <!ELEMENT destination (#PCDATA)>
     <!ELEMENT periode (#PCDATA)>
     <!ELEMENT duree (#PCDATA)>
     <!ELEMENT nbparticipant (#PCDATA)>  
     <!ELEMENT tarifmax (#PCDATA)>
     <!ELEMENT propositions (proposition+)>
     <!ELEMENT proposition (#PCDATA)>

=== Gam1nerie/XML/axl.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE commercial SYSTEM "axl.dtd">

<commercial> 

<client nom="Renard" prenom="Nicolas" mail="nrenard@gmail.com" mobile="0699305567"> 
    <demande>
    <destination>Mexique</destination>
    <periode>Fin mai 2020</periode>
    <duree>7 nuits</duree>
    <nbparticipant>4</nbparticipant>
    <tarifmax>890.00</tarifmax>
    <propositions>
        <proposition>Circuit Maya: Yucatan-Cancùn...</proposition>
        <proposition>Route turquoise: cascades, temples</proposition>
    </propositions>
</demande>
</client>
<client nom="Grenapin" prenom="Dorothée" mail="grenapin@fr-group.com" mobile="0299123455">
</client>
</commercial>
